/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SignalMessage = IDL.Variant({
  'screenShareStop' : IDL.Null,
  'iceCandidate' : IDL.Text,
  'offer' : IDL.Text,
  'screenShareRequest' : IDL.Null,
  'answer' : IDL.Text,
});
export const CallStatus = IDL.Variant({
  'incoming' : IDL.Record({ 'caller' : IDL.Principal }),
  'none' : IDL.Null,
  'inCall' : IDL.Record({
    'screenCaster' : IDL.Opt(IDL.Principal),
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
    'isScreenCasting' : IDL.Bool,
  }),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'answerCall' : IDL.Func([IDL.Null], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSignals' : IDL.Func([IDL.Null], [], []),
  'declineCall' : IDL.Func([IDL.Null], [], []),
  'disableScreenCast' : IDL.Func([IDL.Null], [], []),
  'enableScreenCast' : IDL.Func([IDL.Null], [], []),
  'endCall' : IDL.Func([IDL.Null], [], []),
  'fetchSignals' : IDL.Func([IDL.Null], [IDL.Vec(SignalMessage)], ['query']),
  'getCallStatus' : IDL.Func([IDL.Null], [CallStatus], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPrincipalFromPhoneNumber' : IDL.Func([IDL.Text], [IDL.Principal], []),
  'getUserByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([IDL.Principal], [], []),
  'isAvailable' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendSignal' : IDL.Func([IDL.Principal, SignalMessage], [], []),
  'setAvailable' : IDL.Func([IDL.Null], [], []),
  'setUnavailable' : IDL.Func([IDL.Null], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SignalMessage = IDL.Variant({
    'screenShareStop' : IDL.Null,
    'iceCandidate' : IDL.Text,
    'offer' : IDL.Text,
    'screenShareRequest' : IDL.Null,
    'answer' : IDL.Text,
  });
  const CallStatus = IDL.Variant({
    'incoming' : IDL.Record({ 'caller' : IDL.Principal }),
    'none' : IDL.Null,
    'inCall' : IDL.Record({
      'screenCaster' : IDL.Opt(IDL.Principal),
      'callee' : IDL.Principal,
      'caller' : IDL.Principal,
      'isScreenCasting' : IDL.Bool,
    }),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'answerCall' : IDL.Func([IDL.Null], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSignals' : IDL.Func([IDL.Null], [], []),
    'declineCall' : IDL.Func([IDL.Null], [], []),
    'disableScreenCast' : IDL.Func([IDL.Null], [], []),
    'enableScreenCast' : IDL.Func([IDL.Null], [], []),
    'endCall' : IDL.Func([IDL.Null], [], []),
    'fetchSignals' : IDL.Func([IDL.Null], [IDL.Vec(SignalMessage)], ['query']),
    'getCallStatus' : IDL.Func([IDL.Null], [CallStatus], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPrincipalFromPhoneNumber' : IDL.Func([IDL.Text], [IDL.Principal], []),
    'getUserByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([IDL.Principal], [], []),
    'isAvailable' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendSignal' : IDL.Func([IDL.Principal, SignalMessage], [], []),
    'setAvailable' : IDL.Func([IDL.Null], [], []),
    'setUnavailable' : IDL.Func([IDL.Null], [], []),
  });
};

export const init = ({ IDL }) => { return []; };