/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CallStatus = { 'incoming' : { 'caller' : Principal } } |
  { 'none' : null } |
  {
    'inCall' : {
      'screenCaster' : [] | [Principal],
      'callee' : Principal,
      'caller' : Principal,
      'isScreenCasting' : boolean,
    }
  };
export type SignalMessage = { 'screenShareStop' : null } |
  { 'iceCandidate' : string } |
  { 'offer' : string } |
  { 'screenShareRequest' : null } |
  { 'answer' : string };
export interface UserProfile { 'displayName' : string, 'phoneNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / This function allows the callee to accept an incoming call.
   * / It will update both caller and callee to the `inCall` state if the call is valid.
   */
  'answerCall' : ActorMethod<[null], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearSignals' : ActorMethod<[null], undefined>,
  /**
   * / Decline an incoming call. This will always transition the call state to none.
   */
  'declineCall' : ActorMethod<[null], undefined>,
  'disableScreenCast' : ActorMethod<[null], undefined>,
  'enableScreenCast' : ActorMethod<[null], undefined>,
  'endCall' : ActorMethod<[null], undefined>,
  'fetchSignals' : ActorMethod<[null], Array<SignalMessage>>,
  'getCallStatus' : ActorMethod<[null], CallStatus>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPrincipalFromPhoneNumber' : ActorMethod<[string], Principal>,
  'getUserByPhoneNumber' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initiateCall' : ActorMethod<[Principal], undefined>,
  'isAvailable' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendSignal' : ActorMethod<[Principal, SignalMessage], undefined>,
  'setAvailable' : ActorMethod<[null], undefined>,
  'setUnavailable' : ActorMethod<[null], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];