/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SignalMessage = {
    __kind__: "screenShareStop";
    screenShareStop: null;
} | {
    __kind__: "iceCandidate";
    iceCandidate: string;
} | {
    __kind__: "offer";
    offer: string;
} | {
    __kind__: "screenShareRequest";
    screenShareRequest: null;
} | {
    __kind__: "answer";
    answer: string;
};
export interface UserProfile {
    displayName: string;
    phoneNumber: string;
}
export type CallStatus = {
    __kind__: "incoming";
    incoming: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "inCall";
    inCall: {
        screenCaster?: Principal;
        callee: Principal;
        caller: Principal;
        isScreenCasting: boolean;
    };
};
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    answerCall(callerPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearSignals(arg0: null): Promise<void>;
    disableScreenCast(arg0: null): Promise<void>;
    enableScreenCast(arg0: null): Promise<void>;
    endCall(arg0: null): Promise<void>;
    fetchSignals(arg0: null): Promise<Array<SignalMessage>>;
    getCallStatus(arg0: null): Promise<CallStatus>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPrincipalFromPhoneNumber(phoneNumber: string): Promise<Principal>;
    getUserByPhoneNumber(phoneNumber: string): Promise<UserProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initiateCall(callee: Principal): Promise<void>;
    isAvailable(principal: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendSignal(target: Principal, message: SignalMessage): Promise<void>;
    setAvailable(arg0: null): Promise<void>;
    setUnavailable(arg0: null): Promise<void>;
}
import type { CallStatus as _CallStatus, SignalMessage as _SignalMessage, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async answerCall(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.answerCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.answerCall(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearSignals(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSignals(arg0);
            return result;
        }
    }
    async disableScreenCast(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableScreenCast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableScreenCast(arg0);
            return result;
        }
    }
    async enableScreenCast(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableScreenCast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableScreenCast(arg0);
            return result;
        }
    }
    async endCall(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endCall(arg0);
            return result;
        }
    }
    async fetchSignals(arg0: null): Promise<Array<SignalMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSignals(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSignals(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallStatus(arg0: null): Promise<CallStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallStatus(arg0);
                return from_candid_CallStatus_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallStatus(arg0);
            return from_candid_CallStatus_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrincipalFromPhoneNumber(arg0: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalFromPhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalFromPhoneNumber(arg0);
            return result;
        }
    }
    async getUserByPhoneNumber(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPhoneNumber(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPhoneNumber(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateCall(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateCall(arg0);
            return result;
        }
    }
    async isAvailable(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAvailable(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendSignal(arg0: Principal, arg1: SignalMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSignal(arg0, to_candid_SignalMessage_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSignal(arg0, to_candid_SignalMessage_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setAvailable(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAvailable(arg0);
            return result;
        }
    }
    async setUnavailable(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUnavailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUnavailable(arg0);
            return result;
        }
    }
}
function from_candid_CallStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SignalMessage_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalMessage): SignalMessage {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    screenCaster: [] | [Principal];
    callee: Principal;
    caller: Principal;
    isScreenCasting: boolean;
}): {
    screenCaster?: Principal;
    callee: Principal;
    caller: Principal;
    isScreenCasting: boolean;
} {
    return {
        screenCaster: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.screenCaster)),
        callee: value.callee,
        caller: value.caller,
        isScreenCasting: value.isScreenCasting
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    screenShareStop: null;
} | {
    iceCandidate: string;
} | {
    offer: string;
} | {
    screenShareRequest: null;
} | {
    answer: string;
}): {
    __kind__: "screenShareStop";
    screenShareStop: null;
} | {
    __kind__: "iceCandidate";
    iceCandidate: string;
} | {
    __kind__: "offer";
    offer: string;
} | {
    __kind__: "screenShareRequest";
    screenShareRequest: null;
} | {
    __kind__: "answer";
    answer: string;
} {
    return "screenShareStop" in value ? {
        __kind__: "screenShareStop",
        screenShareStop: value.screenShareStop
    } : "iceCandidate" in value ? {
        __kind__: "iceCandidate",
        iceCandidate: value.iceCandidate
    } : "offer" in value ? {
        __kind__: "offer",
        offer: value.offer
    } : "screenShareRequest" in value ? {
        __kind__: "screenShareRequest",
        screenShareRequest: value.screenShareRequest
    } : "answer" in value ? {
        __kind__: "answer",
        answer: value.answer
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incoming: null;
} | {
    none: null;
} | {
    inCall: {
        screenCaster: [] | [Principal];
        callee: Principal;
        caller: Principal;
        isScreenCasting: boolean;
    };
}): {
    __kind__: "incoming";
    incoming: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "inCall";
    inCall: {
        screenCaster?: Principal;
        callee: Principal;
        caller: Principal;
        isScreenCasting: boolean;
    };
} {
    return "incoming" in value ? {
        __kind__: "incoming",
        incoming: value.incoming
    } : "none" in value ? {
        __kind__: "none",
        none: value.none
    } : "inCall" in value ? {
        __kind__: "inCall",
        inCall: from_candid_record_n8(_uploadFile, _downloadFile, value.inCall)
    } : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignalMessage>): Array<SignalMessage> {
    return value.map((x)=>from_candid_SignalMessage_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SignalMessage_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalMessage): _SignalMessage {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "screenShareStop";
    screenShareStop: null;
} | {
    __kind__: "iceCandidate";
    iceCandidate: string;
} | {
    __kind__: "offer";
    offer: string;
} | {
    __kind__: "screenShareRequest";
    screenShareRequest: null;
} | {
    __kind__: "answer";
    answer: string;
}): {
    screenShareStop: null;
} | {
    iceCandidate: string;
} | {
    offer: string;
} | {
    screenShareRequest: null;
} | {
    answer: string;
} {
    return value.__kind__ === "screenShareStop" ? {
        screenShareStop: value.screenShareStop
    } : value.__kind__ === "iceCandidate" ? {
        iceCandidate: value.iceCandidate
    } : value.__kind__ === "offer" ? {
        offer: value.offer
    } : value.__kind__ === "screenShareRequest" ? {
        screenShareRequest: value.screenShareRequest
    } : value.__kind__ === "answer" ? {
        answer: value.answer
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
